#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_mysql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/${app}_minio.service"
systemctl enable "${app}_minio.service" --quiet
ynh_restore "/etc/systemd/system/${app}_gotrue.service"
systemctl enable "${app}_gotrue.service" --quiet
ynh_restore "/etc/systemd/system/${app}_cloud.service"
systemctl enable "${app}_cloud.service" --quiet
ynh_restore "/etc/systemd/system/${app}_admin_frontend.service"
systemctl enable "${app}_admin_frontend.service" --quiet
ynh_restore "/etc/systemd/system/${app}_ai.service"
systemctl enable "${app}_ai.service" --quiet
ynh_restore "/etc/systemd/system/${app}_worker.service"
systemctl enable "${app}_worker.service" --quiet

yunohost service add ${app}_minio --description="A short description of the app" --log="/var/log/$app/${app}_minio.log"
yunohost service add ${app}_gotrue --description="A short description of the app" --log="/var/log/$app/${app}_gotrue.log"
yunohost service add ${app}_cloud --description="A short description of the app" --log="/var/log/$app/${app}_cloud.log"
yunohost service add ${app}_admin_frontend --description="A short description of the app" --log="/var/log/$app/${app}_admin_frontend.log"
yunohost service add ${app}_ai --description="A short description of the app" --log="/var/log/$app/${app}_ai.log"
yunohost service add ${app}_worker --description="A short description of the app" --log="/var/log/$app/${app}_worker.log"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="${app}_minio" --action="start" --log_path="/var/log/$app/${app}_minio.log" --wait_until="Console:"
ynh_systemctl --service="${app}_gotrue" --action="start" --log_path="/var/log/$app/${app}_gotrue.log" --wait_until="GoTrue API started"
ynh_systemctl --service="${app}_cloud" --action="start" --log_path="/var/log/$app/${app}_cloud.log" --wait_until="Server started"
ynh_systemctl --service="${app}_admin_frontend" --action="start" --log_path="/var/log/$app/${app}_admin_frontend.log" --wait_until="listening on"
ynh_systemctl --service="${app}_ai" --action="start" --log_path="/var/log/$app/${app}_ai.log"
ynh_systemctl --service="${app}_worker" --action="start" --log_path="/var/log/$app/${app}_worker.log" --wait_until="Starting importer worker"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
