#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_docker_image_extract
source ynh_python_install
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}_worker" --action="stop"
ynh_systemctl --service="${app}_ai" --action="stop"
ynh_systemctl --service="${app}_admin_frontend" --action="stop"
ynh_systemctl --service="${app}_gotrue" --action="stop"
ynh_systemctl --service="${app}_cloud" --action="stop"
ynh_systemctl --service="${app}_minio" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
#ynh_script_progression "Ensuring downward compatibility..."

### N.B. : the following setting migration snippets are provided as *EXAMPLES*
### of what you may want to do in some cases (e.g. a setting was not defined on
### some legacy installs and you therefore want to initiaze stuff during upgrade)

# If db_name doesn't exist, create it
# ynh_app_setting_set_default --key=db_name --value="$(ynh_sanitize_dbid --db_name=$app)"

# If install_dir doesn't exist, create it
# ynh_app_setting_set_default --key=install_dir --value="/var/www/$app"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir/appflowy_minio" --source_id="minio" --full_replace
chmod +x "$install_dir/appflowy_minio/minio"

ynh_setup_source --dest_dir="$install_dir/build/pgvector" --source_id="pgvector" 

docker_version="$(ynh_app_upstream_version)"

ynh_docker_image_extract --dest_dir="$install_dir/build/gotrue/" --image_spec="appflowyinc/gotrue:$docker_version"
mkdir -p $install_dir/appflowy_gotrue/migrations/
cp $install_dir/build/gotrue/auth $install_dir/appflowy_gotrue/appflowy_gotrue
rsync -a --delete $install_dir/build/gotrue/migrations/ $install_dir/appflowy_gotrue/migrations/
ynh_safe_rm "$install_dir/build/gotrue/"

ynh_docker_image_extract --dest_dir="$install_dir/build/appflowy_cloud/" --image_spec="appflowyinc/appflowy_cloud:$docker_version"
mkdir -p $install_dir/appflowy_cloud/
cp $install_dir/build/appflowy_cloud/usr/local/bin/appflowy_cloud $install_dir/appflowy_cloud/appflowy_cloud
ynh_safe_rm "$install_dir/build/appflowy_cloud/"

ynh_docker_image_extract --dest_dir="$install_dir/build/admin_frontend/" --image_spec="appflowyinc/admin_frontend:$docker_version"
mkdir -p $install_dir/appflowy_admin_frontend/assets/
cp $install_dir/build/admin_frontend/usr/local/bin/admin_frontend $install_dir/appflowy_admin_frontend/appflowy_admin_frontend
rsync -a --delete $install_dir/build/admin_frontend/app/assets/ $install_dir/appflowy_admin_frontend/assets/
ynh_safe_rm "$install_dir/build/admin_frontend/"

ynh_docker_image_extract --dest_dir="$install_dir/build/appflowy_ai/" --image_spec="appflowyinc/appflowy_ai:0.6.16"
mkdir -p $install_dir/appflowy_ai/
rsync -a --delete $install_dir/build/appflowy_ai/usr/src/app/ $install_dir/appflowy_ai/
ynh_safe_rm "$install_dir/build/appflowy_ai/"

ynh_docker_image_extract --dest_dir="$install_dir/build/appflowy_worker/" --image_spec="appflowyinc/appflowy_worker:$docker_version"
mkdir -p $install_dir/appflowy_worker/
cp $install_dir/build/appflowy_worker/usr/local/bin/appflowy_worker $install_dir/appflowy_worker/appflowy_worker
ynh_safe_rm "$install_dir/build/appflowy_worker/"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="deploy.env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}_minio" --template="appflowy_minio.service"
yunohost service add ${app}_minio --description="A short description of the app" --log="/var/log/$app/${app}_minio.log"

ynh_config_add_systemd --service="${app}_gotrue" --template="appflowy_gotrue.service"
yunohost service add ${app}_gotrue --description="A short description of the app" --log="/var/log/$app/${app}_gotrue.log"

ynh_config_add_systemd --service="${app}_cloud" --template="appflowy_cloud.service"
yunohost service add ${app}_cloud --description="A short description of the app" --log="/var/log/$app/${app}_cloud.log"

ynh_config_add_systemd --service="${app}_admin_frontend" --template="appflowy_admin_frontend.service"
yunohost service add ${app}_admin_frontend --description="A short description of the app" --log="/var/log/$app/${app}_admin_frontend.log"

ynh_config_add_systemd --service="${app}_ai" --template="appflowy_ai.service"
yunohost service add ${app}_ai --description="A short description of the app" --log="/var/log/$app/${app}_ai.log"

ynh_config_add_systemd --service="${app}_worker" --template="appflowy_worker.service"
yunohost service add ${app}_worker --description="A short description of the app" --log="/var/log/$app/${app}_worker.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

# Initializing Gotrue
(
	chmod +x ../conf/supabase_auth.sh
	source $install_dir/.env
	export POSTGRES_DB=$POSTGRES_DB
	export POSTGRES_USER=$POSTGRES_USER
	export SUPABASE_PASSWORD=$SUPABASE_PASSWORD
	../conf/supabase_auth.sh
)

# Installing pgvector
pushd "$install_dir/build/pgvector"
	make
	make install
	ynh_psql_db_shell $db_name <<< "CREATE EXTENSION vector;"
popd

ynh_safe_rm "$install_dir/build/"

# Installing ai
pushd "$install_dir/appflowy_ai"
	PATH=$path_with_python pip install --no-cache-dir poetry
	cd server
	PATH=$path_with_python poetry config virtualenvs.create false && PATH=$path_with_python poetry install --no-root
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="${app}_minio" --action="start" --log_path="/var/log/$app/${app}_minio.log" --wait_until="Console:"
ynh_systemctl --service="${app}_gotrue" --action="start" --log_path="/var/log/$app/${app}_gotrue.log" --wait_until="GoTrue API started"
ynh_systemctl --service="${app}_cloud" --action="start" --log_path="/var/log/$app/${app}_cloud.log" --wait_until="Server started"
ynh_systemctl --service="${app}_admin_frontend" --action="start" --log_path="/var/log/$app/${app}_admin_frontend.log" --wait_until="listening on"
ynh_systemctl --service="${app}_ai" --action="start" --log_path="/var/log/$app/${app}_ai.log"
ynh_systemctl --service="${app}_worker" --action="start" --log_path="/var/log/$app/${app}_worker.log" --wait_until="Starting importer worker"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
